apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http

# kubectl apply -f k8s/backstage-service.yaml

# sudo kubectl port-forward --namespace=backstage svc/backstage 80:80

# # app-config.yaml
# app:
#   baseUrl: http://localhost

# organization:
#   name: Spotify

# backend:
#   baseUrl: http://localhost
#   listen:
#     port: 7007
#   cors:
#     origin: http://localhost

